<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9010a1068656c6c6f776f726c642e70726f746f120a68656c6c6f776f726c64221c0a0c48656c6c6f52657175657374120c0a046e616d6518012001280922200a0d48656c6c6f526573706f6e7365120f0a076d657373616765180120012809324a0a0548656c6c6f12410a0853617948656c6c6f12182e68656c6c6f776f726c642e48656c6c6f526571756573741a192e68656c6c6f776f726c642e48656c6c6f526573706f6e7365220042055a03706266620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

